markdown: maruku
theme: jekyll-theme-cayman
ptitle: ["Latex: écrire en Arabe et en Français"]
description: [Rédiger vos documents et présentations en Latex]
use_math: true
github:
  is_project_page: false
