theme: jekyll-theme-cayman
title: ["Latex: écrire en Arabe et en Français"]
description: [Rédiger vos documents et présentations en Latex]
show_downloads: [false]
docs_list_title: ACME Documentation
docs:

- title: Introduction
  url: introduction.html

- title: Configuration
  url: configuration.html
