theme: jekyll-theme-cayman
site.title: ["Latex: écrire en Arabe et en Français"]
description: [Rédiger vos documents et présentations en Latex]
markdown: maruku
use_math: true
github:
  is_project_page: false
