theme: jekyll-theme-cayman
page.title: [Latex: écrire en Arabe et en Français]
description: [A short description of your site's purpose]
show_downloads: [false]
#google_analytics: [Your Google Analytics tracking ID]
